TEXTS = {
    "fa": {
        "choose_language": "🌐 زبان ربات را انتخاب کن:",
        "welcome": "👋 به ربات چالش خوش آمدی\n\nمن دستیار تو برای ساخت، مدیریت و شرکت در چالش‌ها هستم.\nهرجا گیر کردی، از من بپرس یا از پنل استفاده کن.",
        "main_menu": "✨ پنل اصلی\n\nیک گزینه را انتخاب کن؛ من مرحله‌به‌مرحله همراهت هستم.",
        "btn_active": "🎯 چالش‌های فعال", "btn_new": "➕ ساخت چالش", "btn_results": "🏆 نتایج", "btn_settings": "⚙️ تنظیمات", "btn_about": "ℹ️ درباره ربات", "btn_creator": "👤 سازنده", "btn_back": "↩️ برگشت", "btn_confirm": "✅ تأیید و انتشار", "btn_cancel": "❌ لغو", "btn_fa": "🇦🇫 🇮🇷 فارسی", "btn_en": "🇬🇧 English", "language_saved": "زبان ذخیره شد.", "start_button": "▶️ استارت",
        "ask_title": "🎯 نام چالش\n\nنامی کوتاه و واضح بفرست.\nنمونه: چالش لایکی ویژه",
        "ask_channel": "📢 لینک کانال\n\nلینک عمومی کانالت را بفرست.\nنمونه: https://t.me/channel_name\n\n⚠️ ربات باید در کانال ادمین باشد.",
        "bad_channel": "⚠️ این لینک قابل استفاده نیست.\n\nلطفاً فقط لینک عمومی کانال را مثل نمونه بفرست:\nhttps://t.me/channel_name\n\nهمچنین مطمئن شو ربات در کانال ادمین است.",
        "ask_owner_username": "👑 آیدی برگزارکننده\n\nآیدی عمومی خودت را بفرست.\nنمونه: @cactuc580",
        "bad_username": "⚠️ آیدی درست نیست.\n\nنمونه صحیح: @username",
        "ask_timezone": "🌍 زمان چالش\n\nمنطقه زمانی را انتخاب کن تا ساعت شروع و پایان دقیق ثبت شود:",
        "tz_af": "🇦🇫 افغانستان", "tz_ir": "🇮🇷 ایران", "tz_de": "🇩🇪 آلمان",
        "ask_day": "📅 زمان شروع\n\nمی‌خواهی چالش چه روزی شروع شود؟",
        "today": "🟢 امروز", "tomorrow": "🔵 فردا", "day_after": "🟣 پس‌فردا", "next_week": "📆 یک هفته بعد", "choose_date": "🗓 انتخاب تاریخ",
        "ask_date": "🗓 نوع تاریخ را انتخاب کن\n\nمی‌توانی تاریخ را به میلادی، شمسی ایران یا شمسی افغانستان وارد کنی.",
        "calendar_gregorian": "🌍 میلادی", "calendar_iran": "🇮🇷 شمسی ایران", "calendar_afghan": "🇦🇫 شمسی افغانستان",
        "ask_gregorian_date": "🌍 تاریخ میلادی را بفرست.\n\nنمونه: 2026/10/05",
        "ask_iran_date": "🇮🇷 تاریخ شمسی ایران را بفرست.\n\nنمونه: ۱۴۰۵/۰۷/۱۳ یا 1405/07/13",
        "ask_afghan_date": "🇦🇫 تاریخ شمسی افغانستان را بفرست.\n\nنمونه: ۱۴۰۵/۰۷/۱۳ یا 1405/07/13",
        "bad_date": "⚠️ تاریخ درست نیست.\n\nمثلاً این‌طور بفرست: 2026/10/05 یا ۱۴۰۵/۰۷/۱۳",
        "ask_time": "⏰ ساعت شروع\n\nساعت را با دقیقه بفرست.\nنمونه: 21:30\n\nاگر فقط ساعت را بفرستی، ربات دقیقه را ۰۰ در نظر می‌گیرد. می‌توانی بگویی ۹ شب، ۹ عصر یا ۹ صبح.",
        "bad_time": "⚠️ ساعت درست تشخیص داده نشد.\n\nنمونه‌ها:\n21:30\n۹ شب\n۹ عصر\n۹ صبح",
        "ask_duration": "⏳ مدت چالش\n\nچالش چند ساعت ادامه داشته باشد؟\n\nنمونه: 24 یا 12.5",
        "bad_duration": "⚠️ مدت باید یک عدد مثبت باشد.\n\nنمونه: 24",
        "ask_winners": "🏆 تعداد برنده‌ها\n\nچند نفر برنده نهایی باشند؟\nنمونه: 3",
        "bad_winners": "⚠️ یک عدد بین ۱ تا ۲۰ بفرست.\n\nنمونه: 3",
        "ask_prize": "🎁 جایزه نفر {rank}\n\nمثلاً: ۵۰۰ استارز یا یک هدیه ویژه",
        "ask_rules": "📜 قوانین چالش\n\nقوانین را بنویس. اگر قانون خاصی نداری، بنویس پیش‌فرض.\n\nنمونه: هر شرکت‌کننده فقط یک‌بار می‌تواند لایک کند.",
        "ask_stars": "⭐️ استارز\n\nآیا استارزهای واکنش به پست شرکت‌کننده هم در لایک نهایی حساب شوند؟",
        "yes": "✅ بله", "no": "❌ خیر",
        "ask_rate": "⭐️ ضریب استارز\n\nهر استارز چند لایک حساب شود؟\n\nمثلاً اگر ۲ بفرستی، روی بنر نوشته می‌شود:\n⭐️ هر استارز شما دو لایک حساب می‌شود.",
        "bad_rate": "⚠️ یک عدد بین ۱ تا ۱۰۰ بفرست.\n\nنمونه: 2",
        "preview": "🔍 پیش‌نمایش نهایی چالش",
        "custom_emoji_offer": "🎨 شخصی‌سازی ایموجی\n\nاگر اکانتت پریمیوم است، می‌توانی تا ۶ ایموجی سفارشی خودت را در یک پیام بفرستی.\n\nربات از آن‌ها در بخش‌های اصلی بنر استفاده می‌کند.\n\nاگر نمی‌خواهی تغییر بدهی، «ادامه با ایموجی‌های پیشنهادی» را بزن.",
        "custom_emoji_ask": "🎨 حالا ایموجی‌های پریمیومی خودت را در یک پیام بفرست.\n\nحداکثر ۶ ایموجی کافی است. بهتر است هرکدام را یک‌بار بفرستی.",
        "custom_emoji_bad": "⚠️ ایموجی سفارشی تلگرام پیدا نشد.\n\nاگر پریمیوم داری، چند ایموجی سفارشی را مستقیماً از کیبورد تلگرام در یک پیام بفرست.",
        "published": "🎉 چالش با موفقیت ثبت شد!\n\nبنر چالش در کانال منتشر و پین شد.\n\n👥 شرکت‌کننده‌ها می‌توانند مستقیم از لینک زیر ثبت‌نام کنند و نیازی نیست برای ثبت‌نام به شما پیام خصوصی بدهند.\n\n🔗 لینک ثبت‌نام:\n{link}\n\nاین لینک را در کانال، گروه یا استوری خود به اشتراک بگذار.",
        "active_empty": "🎯 فعلاً چالش فعالی وجود ندارد.", "active_title": "🎯 چالش‌های فعال\n\nیکی را انتخاب کن:", "join": "🎯 مشاهده و شرکت", "challenge_closed": "⛔ این چالش دیگر فعال نیست.",
        "enter_welcome": "👋 به چالش خوش آمدی\n\n🎯 {title}\n🏆 {winners} جایزه در نظر گرفته شده.\n\nمن فقط چند اطلاعات کوتاه ازت می‌پرسم و اگر اشتباهی وارد کنی، همان‌جا راهنمایی‌ات می‌کنم.",
        "ask_name": "👤 نام و نام خانوادگی\n\nاسمت را بفرست.\nنمونه: نوید احمدی",
        "ask_age": "🎂 سن\n\nسنت را به عدد بفرست.\nنمونه: ۲۱",
        "bad_age": "⚠️ سن باید یک عدد بین ۵ تا ۱۰۰ باشد.\n\nنمونه: ۲۱",
        "ask_city": "📍 شهر یا ولایت\n\nمحل زندگی یا ولایتت را بفرست.\nنمونه: هرات یا فرانکفورت",
        "ask_photo": "🖼️ عکس شرکت‌کننده\n\nیک عکس واضح از خودت را به صورت «عکس» بفرست، نه فایل.",
        "already_registered": "ℹ️ تو قبلاً در این چالش ثبت‌نام کرده‌ای.\n\n👤 شماره شرکت‌کننده: {number}",
        "registered": "🎉 ثبت‌نام با موفقیت انجام شد!\n\n👤 شرکت‌کننده شماره {number}\n📍 {city}\n\nخوش آمدی {name}. کارت شرکتت در کانال منتشر شد.\n❤️ حالا می‌توانی برای جمع‌کردن لایک بیشتر تلاش کنی.",
        "channel_required": "⚠️ برای لایک‌کردن باید عضو کانال باشی.", "joined_check": "🔄 بررسی عضویت", "like_added": "❤️ لایک ثبت شد!", "already_liked": "ℹ️ این پست را قبلاً لایک کرده‌ای.", "cannot_like_self": "ℹ️ نمی‌توانی پست خودت را لایک کنی.",
        "stats_none": "📊 فعلاً آمار فعالی برای تو وجود ندارد.",
        "stats_header": "📊 آمار تو\n\n🎯 {title}\n📢 {channel}\n👤 شماره: {number}\n❤️ لایک‌های عادی: {likes}\n⭐️ استارز: {stars}\n✨ لایک معادل استارز: {star_likes}\n🏆 مجموع لایک محاسبه‌شده: {score}\n⏳ باقی‌مانده: {remaining}",
        "owner_none": "📊 هنوز چالش فعالی نداری.\n\nاول یک چالش بساز.", "owner_pick": "📊 چالش خودت را انتخاب کن:",
        "owner_stats": "📊 آمار چالش\n\n🎯 {title}\n📢 {channel}\n👥 ثبت‌نام: {participants}\n🟢 عضو فعلی کانال: {joined}\n❤️ مجموع لایک: {likes}\n⭐️ مجموع استارز: {stars}\n🔗 ورود از لینک: {starts}\n⏳ باقی‌مانده: {remaining}",
        "owner_people": "👥 شرکت‌کنندگان", "owner_board": "🏆 رتبه فعلی",
        "about": "ℹ️ درباره ربات\n\nاین ربات برای ساده‌تر و حرفه‌ای‌تر شدن ساخت و مدیریت چالش‌ها ساخته شده است.\n\n🎯 ساخت چالش\n👥 ثبت‌نام مستقیم\n❤️ مدیریت لایک\n⭐️ شمارش استارز\n🏆 اعلام نتایج\n🚨 گزارش چالش\n\nهدف این است که مالک و شرکت‌کننده هر دو تجربه‌ای ساده و محترمانه داشته باشند.",
        "creator": "👤 سازنده و طراح ربات\n\n〘Cactuc = نــوید〙\n@cactuc580\n\nاین ربات برای راحت‌تر کردن کار مالکین چنل‌ها برای چالش‌ها ساخته شده، امیدواریم که به دردتون بخوره.",
        "results": "🏆 نتایج\n\nنتایج چالش‌های پایان‌یافته در این بخش قرار می‌گیرند.",
        "report_menu": "🚨 گزارش چالش\n\nدلیل گزارش را انتخاب کن:", "report_text": "📝 توضیح گزارش را بفرست.\n\nلطفاً کوتاه و واضح بنویس چه اتفاقی افتاده است.", "report_saved": "✅ گزارش ثبت شد و برای بررسی مدیر ارسال شد.",
        "reminder": "🚨 یک ساعت تا پایان چالش!\n\n🔥 رقابت وارد مرحله آخر شده.\n❤️ هنوز فرصت داری لایک بیشتری جمع کنی.\n{stars}\n🏆 تا آخر ادامه بده!",
        "ended_notice": "⛔ چالش به پایان رسید\n\nثبت‌نام جدید انجام نمی‌شود و لایک‌های جدید از این لحظه برای این چالش حساب نمی‌شوند.\n\n⏱️ اعلام نتایج تا دو دقیقه دیگر انجام می‌شود. لطفاً منتظر باشید.",
        "result_caption": "🏆 نتیجه نهایی چالش\n\n🥇 رتبه: {rank}\n👤 {name}\n📍 {city}\n\n🎁 جایزه: {prize}\n❤️ لایک‌های عادی: {likes}\n⭐️ استارز: {stars}\n✨ لایک معادل استارز: {star_likes}\n🏆 مجموع لایک محاسبه‌شده: {score}\n\nتبریک می‌گوییم و برای همه شرکت‌کننده‌ها موفقیت آرزو داریم!",
        "results_done": "🎊 نتایج چالش اعلام شد!\n\nبرنده‌ها به ترتیب در پیام‌های جداگانه اعلام شدند.",
        "not_allowed": "⛔ اجازه انجام این کار را نداری.", "cancelled": "❌ عملیات لغو شد.",
        "random_message": "👋 سلام! من دستیار ربات چالش هستم.\n\nاگر درباره چالش، ثبت‌نام، ساخت چالش یا آمار سؤال داری، بپرس.\n\nیا از گزینه ▶️ استارت استفاده کن تا پنل را باز کنم.",
    },
    "en": {
        "choose_language": "🌐 Choose your language:", "welcome": "👋 Welcome to the Challenge Bot\n\nI help you create, manage and join challenges.", "main_menu": "✨ Main panel\n\nChoose an option and I’ll guide you step by step.",
        "btn_active": "🎯 Active challenges", "btn_new": "➕ Create challenge", "btn_results": "🏆 Results", "btn_settings": "⚙️ Settings", "btn_about": "ℹ️ About", "btn_creator": "👤 Creator", "btn_back": "↩️ Back", "btn_confirm": "✅ Confirm & publish", "btn_cancel": "❌ Cancel", "btn_fa": "🇦🇫 🇮🇷 فارسی", "btn_en": "🇬🇧 English", "language_saved": "Language saved.", "start_button": "▶️ Start",
        "ask_title": "🎯 Challenge title\n\nExample: Special Like Challenge", "ask_channel": "📢 Channel link\n\nExample: https://t.me/channel_name\n\nThe bot must be an admin.", "bad_channel": "⚠️ Send a public channel link like:\nhttps://t.me/channel_name\n\nMake sure the bot is an admin.", "ask_owner_username": "👑 Organizer username\n\nExample: @username", "bad_username": "⚠️ Example: @username", "ask_timezone": "🌍 Challenge time\n\nChoose the timezone:", "tz_af": "🇦🇫 Afghanistan", "tz_ir": "🇮🇷 Iran", "tz_de": "🇩🇪 Germany", "ask_day": "📅 Start day\n\nWhen should it start?", "today": "🟢 Today", "tomorrow": "🔵 Tomorrow", "day_after": "🟣 Day after tomorrow", "next_week": "📆 One week later", "choose_date": "🗓 Choose date", "ask_date": "🗓 Choose a calendar:", "calendar_gregorian": "🌍 Gregorian", "calendar_iran": "🇮🇷 Iranian Solar", "calendar_afghan": "🇦🇫 Afghan Solar", "ask_gregorian_date": "🌍 Send Gregorian date.\nExample: 2026/10/05", "ask_iran_date": "🇮🇷 Send Iranian Solar date.\nExample: 1405/07/13", "ask_afghan_date": "🇦🇫 Send Afghan Solar date.\nExample: 1405/07/13", "bad_date": "⚠️ Invalid date. Example: 2026/10/05 or 1405/07/13", "ask_time": "⏰ Start time\n\nExamples: 21:30, 9 pm, 9 شب", "bad_time": "⚠️ Invalid time. Examples: 21:30, 9 pm, 9 شب", "ask_duration": "⏳ Duration\n\nExample: 24", "bad_duration": "⚠️ Send a positive number. Example: 24", "ask_winners": "🏆 Number of winners\n\nExample: 3", "bad_winners": "⚠️ Send a number from 1 to 20.", "ask_prize": "🎁 Prize for rank {rank}\n\nExample: 500 Stars", "ask_rules": "📜 Rules\n\nSend your rules or type default.", "ask_stars": "⭐️ Stars\n\nShould Stars reactions count toward the final likes?", "yes": "✅ Yes", "no": "❌ No", "ask_rate": "⭐️ Stars rate\n\nHow many Likes should one Star count as?\nExample: 2", "bad_rate": "⚠️ Send a number from 1 to 100.", "preview": "🔍 Final preview", "custom_emoji_offer": "🎨 Customize emojis\n\nIf you have Telegram Premium, you can send up to 6 custom emojis in one message.", "custom_emoji_ask": "🎨 Send your custom emojis in one message.", "custom_emoji_bad": "⚠️ No Telegram custom emoji was detected.", "published": "🎉 Challenge published successfully!\n\nThe banner was posted and pinned.\n\nParticipants can register directly using this link:\n{link}", "active_empty": "🎯 No active challenges right now.", "active_title": "🎯 Active challenges\n\nChoose one:", "join": "🎯 View & join", "challenge_closed": "⛔ This challenge is no longer active.", "enter_welcome": "👋 Welcome to the challenge\n\n🎯 {title}\n🏆 {winners} prizes\n\nI’ll guide you step by step.", "ask_name": "👤 Name\n\nExample: John Smith", "ask_age": "🎂 Age\n\nExample: 21", "bad_age": "⚠️ Age must be 5–100.", "ask_city": "📍 City / province\n\nExample: Herat", "ask_photo": "🖼️ Participant photo\n\nSend a clear photo as a photo, not a file.", "already_registered": "ℹ️ You are already registered.\n\nParticipant #{number}", "registered": "🎉 Registration successful!\n\nParticipant #{number}\n\nYour card was posted to the channel.", "channel_required": "⚠️ Join the channel before liking.", "joined_check": "🔄 Check membership", "like_added": "❤️ Like recorded!", "already_liked": "ℹ️ You already liked this post.", "cannot_like_self": "ℹ️ You cannot like your own post.", "stats_none": "📊 No active stats are available.", "stats_header": "📊 Your stats\n\n🎯 {title}\n❤️ Normal likes: {likes}\n⭐️ Stars: {stars}\n✨ Star-equivalent likes: {star_likes}\n🏆 Calculated total likes: {score}\n⏳ Remaining: {remaining}", "owner_none": "📊 You have no active challenges.", "owner_pick": "📊 Choose your challenge:", "owner_stats": "📊 Challenge stats\n\n🎯 {title}\n👥 Registrations: {participants}\n🟢 Current members: {joined}\n❤️ Likes: {likes}\n⭐️ Stars: {stars}\n🔗 Link starts: {starts}\n⏳ Remaining: {remaining}", "owner_people": "👥 Participants", "owner_board": "🏆 Leaderboard", "about": "ℹ️ About\n\nA challenge assistant for creating and managing channel challenges.", "creator": "👤 Creator\n\n〘Cactuc = نــوید〙\n@cactuc580", "results": "🏆 Results\n\nFinished challenge results will appear here.", "report_menu": "🚨 Report challenge\n\nChoose a reason:", "report_text": "📝 Send report details:", "report_saved": "✅ Report submitted.", "reminder": "🚨 One hour left!\n\n❤️ You can still collect more likes.\n{stars}", "ended_notice": "⛔ Challenge ended\n\nNew registrations and new likes are no longer counted.\n\nResults will be announced in about two minutes.", "result_caption": "🏆 Final challenge result\n\n🥇 Rank: {rank}\n👤 {name}\n📍 {city}\n\n🎁 Prize: {prize}\n❤️ Normal likes: {likes}\n⭐️ Stars: {stars}\n✨ Star-equivalent likes: {star_likes}\n🏆 Calculated total likes: {score}", "results_done": "🎊 Results announced!", "not_allowed": "⛔ Not allowed.", "cancelled": "❌ Cancelled.", "random_message": "👋 Hi! I’m the Challenge Bot assistant.\n\nAsk me about challenges, registration, creation or stats.\n\nOr use ▶️ Start to open the panel.",
    }
}

def t(lang, key, **kwargs):
    text = TEXTS.get(lang, TEXTS["fa"]).get(key) or TEXTS["en"].get(key, key)
    return text.format(**kwargs)
